pipeline: New Cyclonus NPM windows only pipeline

diff --git a/.pipelines/npm/npm-cyc-win-tests-latest-release.yaml b/.pipelines/npm/npm-cyc-win-tests-latest-release.yaml
--- a/.pipelines/npm/npm-cyc-win-tests-latest-release.yaml
+++ b/.pipelines/npm/npm-cyc-win-tests-latest-release.yaml
@@ -78,6 +78,12 @@ jobs:
             echo "Creating resource group named $CLUSTER_NAME"
             az group create --name $CLUSTER_NAME -l $(LOCATION) -o table
 
+            if [ $? != 0 ]
+            then
+            echo "Failing fast since previous command failed"
+            exit 1
+            fi
+
             echo "Creating resource group named $CLUSTER_NAME"
             az aks create \
                 --resource-group $CLUSTER_NAME \
@@ -91,6 +97,12 @@ jobs:
                 --kubernetes-version v1.23.5 \
                 --node-count 1
 
+            if [ $? != 0 ]
+            then
+            echo "Failing fast since previous command failed"
+            exit 1
+            fi
+
             # don't schedule anything on the linux system pool
             echo "Updating $CLUSTER_NAME to not schedule anything on linux pool..."
             az aks nodepool update \
@@ -98,6 +110,12 @@ jobs:
               -g $CLUSTER_NAME \
               -n nodepool1 \
               --node-taints CriticalAddonsOnly=true:NoSchedule
+
+            if [ $? != 0 ]
+            then
+            echo "Failing fast since previous command failed"
+            exit 1
+            fi
 
             echo "Adding Windows nodepool to $CLUSTER_NAME"
             az aks nodepool add \
@@ -108,6 +126,12 @@ jobs:
                 --os-sku Windows2022 \
                 --node-vm-size Standard_D4s_v3 \
                 --node-count 3
+
+            if [ $? != 0 ]
+            then
+            echo "Failing fast since previous command failed"
+            exit 1
+            fi
 
             echo "Getting credentials to $CLUSTER_NAME"
             az aks get-credentials -g $CLUSTER_NAME -n $CLUSTER_NAME --overwrite-existing --file ./kubeconfig
