wip

diff --git a/.pipelines/npm/npm-conformance-tests.yaml b/.pipelines/npm/npm-conformance-tests.yaml
--- a/.pipelines/npm/npm-conformance-tests.yaml
+++ b/.pipelines/npm/npm-conformance-tests.yaml
@@ -200,7 +200,7 @@ jobs:
               fi
 
               az aks get-credentials -n $(AZURE_CLUSTER) -g $(RESOURCE_GROUP) --file ./kubeconfig
-              ./kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/Azure/azure-container-networking/master/npm/examples/windows/azure-npm.yaml
+              ./kubectl --kubeconfig=./kubeconfig apply -f ./npm/examples/windows/azure-npm.yaml
               ./kubectl --kubeconfig=./kubeconfig set image daemonset/azure-npm-win -n kube-system azure-npm=$IMAGE_REGISTRY/azure-npm:windows-amd64-ltsc2022-$(TAG)
 
             else
@@ -219,13 +219,13 @@ jobs:
               az aks get-credentials -n $(AZURE_CLUSTER) -g $(RESOURCE_GROUP) --file ./kubeconfig
 
               # deploy azure-npm
-              ./kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/Azure/azure-container-networking/master/npm/azure-npm.yaml
+              ./kubectl --kubeconfig=./kubeconfig apply -f ./npm/azure-npm.yaml
 
               # swap azure-npm image with one built during run
               ./kubectl --kubeconfig=./kubeconfig set image daemonset/azure-npm -n kube-system azure-npm=$IMAGE_REGISTRY/azure-npm:linux-amd64-$(TAG)
 
               # swap NPM profile with one specified as parameter
-              ./kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/Azure/azure-container-networking/master/npm/profiles/$(PROFILE).yaml
+              ./kubectl --kubeconfig=./kubeconfig apply -f ./npm/profiles/$(PROFILE).yaml
               ./kubectl --kubeconfig=./kubeconfig rollout restart ds azure-npm -n kube-system
             fi
 
@@ -345,14 +345,14 @@ jobs:
           done
 
           exit $exitCode
-        displayName: "Run Test Suite and Get Logs"
+        displayName: "$(PROFILE) - Run Test Suite and Get Logs"
         failOnStderr: false
 
       - publish: $(System.DefaultWorkingDirectory)/npmLogs_$(AZURE_CLUSTER)
         condition: always()
         artifact: NpmLogs_$(AZURE_CLUSTER)
 
-  - job: Create_Windows_Cluster_and_Run_Test
+  - job: Create_Windows_Cyclonus_Cluster_and_Run_Test
     timeoutInMinutes: 360
     displayName: "Run Windows Cyclonus"
     pool:
@@ -436,7 +436,7 @@ jobs:
             chmod +x kubectl
 
             # deploy azure-npm
-            ./kubectl --kubeconfig=./kubeconfig apply -f https://raw.githubusercontent.com/Azure/azure-container-networking/master/npm/examples/windows/azure-npm.yaml
+            ./kubectl --kubeconfig=./kubeconfig apply -f ./npm/examples/windows/azure-npm.yaml
 
             # swap azure-npm image with one built during run
             ./kubectl --kubeconfig=./kubeconfig set image daemonset/azure-npm-win -n kube-system azure-npm=$IMAGE_REGISTRY/azure-npm:windows-amd64-ltsc2022-$(TAG)
@@ -489,6 +489,162 @@ jobs:
         condition: always()
         artifact: NpmLogs-$(RESOURCE_GROUP)-$(PROFILE)
 
+  
+  - job: Create_Windows_Scale_Cluster_and_Run_Test
+    timeoutInMinutes: 360
+    displayName: "Run Windows Scale Test"
+    pool:
+      name: $(BUILD_POOL_NAME_DEFAULT)
+      demands:
+        - agent.os -equals Linux
+        - Role -equals Build
+    dependsOn: [containerize, setup]
+    variables:
+      RESOURCE_GROUP: $[ dependencies.setup.outputs['EnvironmentalVariables.RESOURCE_GROUP'] ]
+      TAG: $[ dependencies.setup.outputs['EnvironmentalVariables.TAG'] ]
+      FQDN: empty
+    strategy:
+      matrix:
+        v2-windows:
+          PROFILE: "scale-ws22"
+    steps:
+      - checkout: self
+      - task: AzureCLI@2
+        displayName: "Create AKS Cluster"
+        inputs:
+          azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
+          scriptType: "bash"
+          scriptLocation: "inlineScript"
+          failOnStderr: true
+          inlineScript: |
+            az extension add --name aks-preview
+            az extension update --name aks-preview
+
+            export CLUSTER_NAME=$(RESOURCE_GROUP)-$(PROFILE)
+
+            echo "Creating resource group named $CLUSTER_NAME"
+            az group create --name $CLUSTER_NAME -l $(LOCATION) -o table
+
+            echo "Creating resource group named $CLUSTER_NAME"
+            az aks create \
+                --resource-group $CLUSTER_NAME \
+                --name $CLUSTER_NAME \
+                --generate-ssh-keys \
+                --windows-admin-username e2eadmin \
+                --windows-admin-password alpha@numeric!password2 \
+                --network-plugin azure \
+                --vm-set-type VirtualMachineScaleSets \
+                --node-vm-size Standard_D4s_v3 \
+                --node-count 1
+
+            # don't schedule anything on the linux system pool
+            echo "Updating $CLUSTER_NAME to not schedule anything on linux pool..."
+            az aks nodepool update \
+              --cluster-name $CLUSTER_NAME \
+              -g $CLUSTER_NAME \
+              -n nodepool1 \
+              --node-taints CriticalAddonsOnly=true:NoSchedule
+
+            echo "Adding Windows nodepool to $CLUSTER_NAME"
+            az aks nodepool add \
+                --resource-group $CLUSTER_NAME \
+                --cluster-name $CLUSTER_NAME \
+                --name awin22 \
+                --os-type Windows \
+                --os-sku Windows2022 \
+                --node-vm-size Standard_D4s_v3 \
+                --node-count 3
+
+            echo "Getting credentials to $CLUSTER_NAME"
+            az aks get-credentials -g $CLUSTER_NAME -n $CLUSTER_NAME --overwrite-existing --file ./kubeconfig
+            mkdir -p ~/.kube/
+            cp ./kubeconfig ~/.kube/config
+
+      - task: AzureCLI@2
+        displayName: "Deploy NPM to Test Cluster"
+        inputs:
+          azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
+          scriptType: "bash"
+          scriptLocation: "inlineScript"
+          failOnStderr: true
+          inlineScript: |
+            export CLUSTER_NAME=$(RESOURCE_GROUP)-$(PROFILE)
+
+            curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl
+            chmod +x kubectl
+
+            # deploy azure-npm
+            ./kubectl --kubeconfig=./kubeconfig apply -f ./npm/examples/windows/azure-npm.yaml
+
+            # swap azure-npm image with one built during run
+            ./kubectl --kubeconfig=./kubeconfig set image daemonset/azure-npm-win -n kube-system azure-npm=$IMAGE_REGISTRY/azure-npm:windows-amd64-ltsc2022-$(TAG)
+
+            echo "sleeping 3 minutes to allow NPM pods to restart"
+            sleep 180
+
+            ./kubectl --kubeconfig=./kubeconfig get po -n kube-system -owide -A
+
+            echo "Showing cluster status for $CLUSTER_NAME"
+            FQDN=`az aks show -n $CLUSTER_NAME -g $CLUSTER_NAME --query fqdn -o tsv`
+            echo "##vso[task.setvariable variable=FQDN]$FQDN"
+
+      - script: |
+          cd test/scale/
+          ./test-scale.sh --max-kwok-pods-per-node=50 \
+              --num-kwok-deployments=10 \
+              --num-kwok-replicas=1 \
+              --max-real-pods-per-node=30 \
+              --num-real-deployments=3 \
+              --num-real-replicas=4 \
+              --num-network-policies=1 \
+              --num-unapplied-network-policies=10 \
+              --num-unique-labels-per-pod=2 \
+              --num-unique-labels-per-deployment=2 \
+              --num-shared-labels-per-pod=10 \
+              --delete-labels \
+              --delete-labels-interval=30 \
+              --delete-labels-times=2 \
+              --delete-netpols \
+              --delete-netpols-interval=0 \
+              --delete-netpols-times=1 \
+              --delete-kwok-pods=10 \
+              --delete-real-pods=6 \
+              --delete-pods-interval=120 \
+              --delete-pods-times=2
+          cd connectivity/
+          ./test-connectivity.sh --num-scale-pods-to-verify=all \
+              --max-wait-for-initial-connectivity=600 \
+              --max-wait-after-adding-netpol=120
+        name: scaletest
+        displayName: "Run Scale Test"
+        failOnStderr: true
+        condition: always()
+
+      - bash: |
+          export CLUSTER_NAME=$(RESOURCE_GROUP)-$(PROFILE)
+          cp cyclonus-$CLUSTER_NAME $(System.DefaultWorkingDirectory)/$CLUSTER_NAME/cyclonus-$CLUSTER_NAME
+          echo "Getting cluster state for $CLUSTER_NAME"
+          mkdir -p $(System.DefaultWorkingDirectory)/$CLUSTER_NAME
+          kubectl get pods -n kube-system | grep npm
+          kubectl logs -n kube-system -l k8s-app=azure-npm --tail -1 --prefix > $(System.DefaultWorkingDirectory)/$CLUSTER_NAME/npm-logs_$(PROFILE).txt
+          # capture any previous logs in case there was a crash
+          npmPodList=`kubectl get pods -n kube-system | grep npm | awk '{print $1}'`
+          for npmPod in $npmPodList; do
+              previousLogFile=$(System.DefaultWorkingDirectory)/$CLUSTER_NAME/previous-npm-logs_$(PROFILE).txt
+              kubectl logs -n kube-system $npmPod -p > $previousLogFile
+              if [[ $? -ne 0 ]]; then
+                  # remove the empty file if kubectl logs failed (e.g. there was no previous terminated container)
+                  rm $previousLogFile
+              fi
+          done
+          cp ./kubeconfig $(System.DefaultWorkingDirectory)/$CLUSTER_NAME/.kubeconfig
+        condition: always()
+
+      - publish: $(System.DefaultWorkingDirectory)/$(RESOURCE_GROUP)-$(PROFILE)
+        condition: always()
+        artifact: NpmLogs-$(RESOURCE_GROUP)-$(PROFILE)
+
+
   - job: clean_up
     displayName: "Cleanup"
     pool:
@@ -497,7 +653,7 @@ jobs:
         - agent.os -equals Linux
         - Role -equals Build
     dependsOn:
-      [Create_Cluster_and_Run_Test, Create_Windows_Cluster_and_Run_Test, setup]
+      [Create_Cluster_and_Run_Test, Create_Windows_Cyclonus_Cluster_and_Run_Test, Create_Windows_Scale_Cluster_and_Run_Test, setup]
     variables:
       RESOURCE_GROUP: $[ dependencies.setup.outputs['EnvironmentalVariables.RESOURCE_GROUP'] ]
     steps:
