Edit Pipeline Trigger

diff --git a/.pipelines/templates/run-unit-tests.yaml b/.pipelines/templates/run-unit-tests.yaml
--- a/.pipelines/templates/run-unit-tests.yaml
+++ b/.pipelines/templates/run-unit-tests.yaml
@@ -1,115 +1,193 @@
 stages:
-  - stage: test
-    displayName: Test ACN
-    dependsOn:
-      - setup
-    jobs:
-      - job: test
-        displayName: Run Tests
-        variables:
-          STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
-        pool:
-          name: "$(BUILD_POOL_NAME_DEFAULT)"
-        steps:
-          - script: |
-              set -e
-              make tools
+- stage: unittest
+  displayName: "Project Unit Tests"
+  dependsOn:
+  - setup
+  variables:
+    STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
+    ACN_DIR: azure-container-networking
+  jobs:
+  - job: linux
+    displayName: "Run All"
+    pool:
+      type: linux
+      #isCustom: true
+      #name: "$(BUILD_POOL_NAME_DEFAULT)"
+    variables:
+      ob_outputDirectory: $(Build.ArtifactStagingDirectory)/linux-unittest
+      REPORT_DIR: $(Build.ArtifactStagingDirectory)/linux-unittest
+      REPORT_XML: $(Build.ArtifactStagingDirectory)/linux-unittest/report.xml
+      COVERAGE_OUT: $(Build.ArtifactStagingDirectory)/linux-unittest/linux-coverage.out
+    steps:
+    - checkout: azure-container-networking
 
-              # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml),
-              # stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code.
-              # Read all output from fd 4 (output from tee) and write to top stdout
-              { { { {
-                    sudo -E env "PATH=$PATH" make test-all;
-                    echo $? >&3;
-                    } | tee >(build/tools/bin/go-junit-report > report.xml) >&4;
-                  } 3>&1;
-                } | { read xs; exit $xs; }
-              } 4>&1
+    - task: GoTool@0
+      inputs:
+        version: '$(GOVERSION)'
 
-              mv coverage-all.out linux-coverage.out
-            retryCountOnTaskFailure: 3
-            name: "Test"
-            displayName: "Run Tests"
-          - task: PublishPipelineArtifact@1
-            inputs:
-              targetPath: 'linux-coverage.out'
-              artifactName: 'linux-coverage'
+    - script: |
+        set -e
+        BIN_INSTALL_DIR=$(realpath bin)
+        GOBIN="$BIN_INSTALL_DIR" go install github.com/jstemmer/go-junit-report/v2@latest
+        JUNIT_REPORT_BIN="$BIN_INSTALL_DIR/go-junit-report"
 
-  - stage: test_windows
-    displayName: Test ACN Windows
-    dependsOn:
-      - setup
-    jobs:
-      - job: test
-        displayName: Run Tests
-        variables:
-          STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
-        pool:
-          name: "$(BUILD_POOL_NAME_DEFAULT_WINDOWS_ALT)"
-        steps:
-          # Only run one go test per script
-          - script: |
-              cd azure-container-networking/
-              go test -timeout 30m -covermode atomic -coverprofile=windows-coverage.out ./npm/... ./cni/... ./platform/...
+        mkdir -p "$REPORT_DIR"
+        touch "$REPORT_XML"
+        make tools
+
+        # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml),
+        # stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code.
+        # Read all output from fd 4 (output from tee) and write to to stdout
+        { { { {
+              sudo -E env "PATH=$PATH" make test-all;
+              echo $? >&3;
+              } | tee >($JUNIT_REPORT_BIN > "$REPORT_XML") >&4;
+            } 3>&1;
+          } | { read xs; exit $xs; }
+        } 4>&1
+
+        ls -la "$REPORT_DIR"
+        mv coverage-all.out "$COVERAGE_OUT"
+        ls -la "$REPORT_DIR"
+      retryCountOnTaskFailure: 3
+      displayName: "Run Unit Tests - Linux"
+      workingDirectory: $(ACN_DIR)
+
+    - script: |
+        BIN_INSTALL_DIR=$(realpath bin)
+        GOBIN="$BIN_INSTALL_DIR" go install github.com/axw/gocov/gocov@latest
+        GOBIN="$BIN_INSTALL_DIR" go install github.com/AlekSi/gocov-xml@latest
+
+        GOCOV_BIN="$BIN_INSTALL_DIR/gocov"
+        GOCOV_XML_BIN="$BIN_INSTALL_DIR/gocov-xml"
+
+        mkdir -p "$REPORT_DIR"
+        touch "$REPORT_XML"
+        make tools
+
+        $GOCOV_BIN convert "$COVERAGE_OUT" > "$REPORT_DIR"/linux-coverage.json
+        $GOCOV_XML_BIN < "$REPORT_DIR"/linux-coverage.json > "$REPORT_DIR"/linux-coverage.gocov.xml
+      displayName: "Generate Test Reporting"
+      workingDirectory: $(ACN_DIR)
+
+
+  - job: windows
+    displayName: "Run Tests - Windows"
+    pool:
+      type: windows
+    variables:
+      ob_outputDirectory: $(Build.ArtifactStagingDirectory)/windows-unittest
+
+      REPORT_DIR: $(Build.ArtifactStagingDirectory)/windows-unittest
+      REPORT_XML: $(Build.ArtifactStagingDirectory)/windows-unittest/report.xml
+      COVERAGE_OUT: $(Build.ArtifactStagingDirectory)/windows-unittest/windows-coverage.out
+    steps:
+    - checkout: azure-container-networking
+
+    - task: GoTool@0
+      inputs:
+        version: '$(GOVERSION)'
+
+    - script: |
+        set -e
+        BIN_INSTALL_DIR=$(realpath bin)
+        GOBIN="$BIN_INSTALL_DIR" go install github.com/jstemmer/go-junit-report/v2@latest
+        JUNIT_REPORT_BIN="$BIN_INSTALL_DIR/go-junit-report"
+
+        mkdir -p "$REPORT_DIR"
+        touch "$REPORT_XML"
+        make tools
+
+        # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml),
+        # stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code.
+        # Read all output from fd 4 (output from tee) and write to to stdout
+        { { { {
+$(COVER_PKG)/...
+              go test -timeout 30m -mod=readonly -buildvcs=false -tags "unit" --skip 'TestE2E*' -race -covermode atomic -coverprofile=windows-coverage.out ./npm/... ./cni/... ./platform/...
               go tool cover -func=windows-coverage.out
-            retryCountOnTaskFailure: 3
-            name: "TestWindows"
-            displayName: "Run Windows Tests"
-          - task: PublishPipelineArtifact@1
-            inputs:
-              targetPath: 'windows-coverage.out'
-              artifactName: 'windows-coverage'
+              echo $? >&3;
+              } | tee >($JUNIT_REPORT_BIN > "$REPORT_XML") >&4;
+            } 3>&1;
+          } | { read xs; exit $xs; }
+        } 4>&1
 
-  - stage: code_coverage
-    displayName: Code Coverage Check
+        ls -la "$REPORT_DIR"
+        mv windows-coverage.out "$COVERAGE_OUT"
+        ls -la "$REPORT_DIR"
+      retryCountOnTaskFailure: 3
+      displayName: "Run Unit Tests - Windows"
+      workingDirectory: $(ACN_DIR)
+
+    - script: |
+        BIN_INSTALL_DIR=$(realpath bin)
+        GOBIN="$BIN_INSTALL_DIR" go install github.com/axw/gocov/gocov@latest
+        GOBIN="$BIN_INSTALL_DIR" go install github.com/AlekSi/gocov-xml@latest
+
+        GOCOV_BIN="$BIN_INSTALL_DIR/gocov"
+        GOCOV_XML_BIN="$BIN_INSTALL_DIR/gocov-xml"
+
+        mkdir -p "$REPORT_DIR"
+        touch "$REPORT_XML"
+        make tools
+
+        $GOCOV_BIN convert "$COVERAGE_OUT" > "$REPORT_DIR"/windows-coverage.json
+        $GOCOV_XML_BIN < "$REPORT_DIR"/windows-coverage.json > "$REPORT_DIR"/windows-coverage.gocov.xml
+      displayName: "Generate Test Reporting"
+      workingDirectory: $(ACN_DIR)
+
+
+  - job: coverage
+    displayName: "Check Test Coverage"
+    condition: always()
     dependsOn:
-      - test
-      - test_windows
-    jobs:
-      - job: coverage
-        displayName: Check Coverage
-        pool:
-          name: "$(BUILD_POOL_NAME_DEFAULT)"
-        steps:
-          - task: DownloadPipelineArtifact@2
-            inputs:
-              artifact: 'linux-coverage'
-              path: './'
-          - task: DownloadPipelineArtifact@2
-            inputs:
-              artifact: 'windows-coverage'
-              path: './'
-          - bash: |
-              make tools
-              sudo ln -s $(pwd)/build/tools/bin/gocov /usr/local/bin/gocov
-              sudo ln -s $(pwd)/build/tools/bin/gocov-xml /usr/local/bin/gocov-xml
+    - windows
+    - linux
+    pool:
+      type: linux
+    variables:
+      ob_outputDirectory: $(Build.ArtifactStagingDirectory)/out
+    steps:
+    - script: |
+        mkdir coverage
 
-              GOOS=linux gocov convert linux-coverage.out > linux-coverage.json
-              GOOS=linux gocov-xml < linux-coverage.json > linux-coverage.xml
+    - task: DownloadPipelineArtifact@2
+      inputs:
+        artifact: drop_unittest_linux
+        targetPath: coverage
 
-              GOOS=windows gocov convert windows-coverage.out > windows-coverage.json
-              GOOS=windows gocov-xml < windows-coverage.json > windows-coverage.xml
+    - task: DownloadPipelineArtifact@2
+      inputs:
+        artifact: drop_unittest_windows
+        targetPath: coverage
 
-              mkdir coverage
+    - task: PublishTestResults@2
+      displayName: "Publish Test Results"
+      inputs:
+        testResultsFormat: 'JUnit'
+        testResultsFiles:  # string. Required. Test results files. Default: **/TEST-*.xml.
+        searchFolder: coverage/**/*.gocov.xml
+        failTaskOnFailedTests: true
+        failTaskOnMissingResultsFile: false
+        #testRunTitle: # Name of the test runs
+        #mergeTestResults: false # boolean. Merge test results. Default: false.
+        #failTaskOnFailureToPublishResults: false # boolean. Fail if there is failure in publishing test results. Default: false.
+      # Advanced
+        #buildPlatform: windows/amd64
+        #buildConfiguration: # string. Alias: configuration. Build Configuration.
+        publishRunAttachments: true
 
-              mv linux-coverage.xml coverage/
-              mv windows-coverage.xml coverage/
-            name: "Coverage"
-            displayName: "Generate Coverage Report"
-            condition: always()
-          - task: PublishCodeCoverageResults@2
-            displayName: "Publish Code Coverage Report"
-            condition: always()
-            inputs:
-              summaryFileLocation: coverage/*
-          - task: BuildQualityChecks@8
-            displayName: "Check Code Coverage Regression"
-            condition: always()
-            inputs:
-              checkCoverage: true
-              coverageFailOption: "build"
-              coverageType: "lines"
-              fallbackOnPRTargetBranch: false
-              baseBranchRef: "master"
-              allowCoverageVariance: true
-              coverageVariance: 0.25
+    - task: PublishCodeCoverageResults@2
+      displayName: "Publish Code Coverage Report"
+      inputs:
+        summaryFileLocation: coverage/*
+
+    - task: BuildQualityChecks@8
+      displayName: "Check Code Coverage Regression"
+      inputs:
+        checkCoverage: true
+        coverageFailOption: "build"
+        coverageType: "lines"
+        fallbackOnPRTargetBranch: false
+        baseBranchRef: "master"
+        allowCoverageVariance: true
+        coverageVariance: 0.25
