skip connectivity test

diff --git a/.pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml b/.pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
--- a/.pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
+++ b/.pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
@@ -116,16 +116,16 @@ steps:
     displayName: "Validate Node Restart"
     retryCountOnTaskFailure: 3
 
-  - script: |
-      set -e
-      echo "Run Cilium Connectivity Tests"
-      cilium status
-      cilium connectivity test --connect-timeout 4s --request-timeout 30s --test '!pod-to-pod-encryption,!node-to-node-encryption,!no-unexpected-packet-drops,!check-log-errors' --force-deploy
-      ns=`kubectl get ns | grep cilium-test | awk '{print $1}'`
-      echo "##vso[task.setvariable variable=ciliumNamespace]$ns"
-    retryCountOnTaskFailure: 3
-    name: "ciliumConnectivityTests"
-    displayName: "Run Cilium Connectivity Tests"
+  #- script: |
+  #    set -e
+  #    echo "Run Cilium Connectivity Tests"
+  #    cilium status
+  #    cilium connectivity test --connect-timeout 4s --request-timeout 30s --test '!pod-to-pod-encryption,!node-to-node-encryption,!no-unexpected-packet-drops,!check-log-errors' --force-deploy
+  #    ns=`kubectl get ns | grep cilium-test | awk '{print $1}'`
+  #    echo "##vso[task.setvariable variable=ciliumNamespace]$ns"
+  #  retryCountOnTaskFailure: 3
+  #  name: "ciliumConnectivityTests"
+  #  displayName: "Run Cilium Connectivity Tests"
 
   - script: |
       set -e
